namespace Mavlink.Protocol.Generator;

internal static class MavlinkGeneratorConstants
{
	public const string AutoGeneratedHeader =
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Mavlink.Protocol.Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

	public const string TypesNamespace = "MavlinkTypes";

	public const string MessagesPostfix = "MavlinkMessage";

	public const string ImmutableArrayNamespace = "System.Collections.Immutable.ImmutableArray";
}
