<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.ComponentModel.Annotations" />
  </ItemGroup>
</Project>
