<Project ToolsVersion="15.0">
  <ItemGroup>
	<!-- Uno -->
    <PackageVersion Include="Uno.WinUI" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.RemoteControl" Version="$(UnoVersion)" />
	<PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.Skia.Gtk" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.Skia.Linux.FrameBuffer" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.Skia.Wpf" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.WebAssembly" Version="$(UnoVersion)" />  
  
	<!-- Wasm -->
    <PackageVersion Include="Uno.Wasm.Bootstrap" Version="$(WasmVersion)" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.DevServer" Version="$(WasmVersion)" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.Server" Version="$(WasmVersion)" />  
 
	<!-- Uno Toolkit -->
	<PackageVersion Include="Uno.Toolkit.WinUI" Version="$(UnoToolkitVersion)" />
	<PackageVersion Include="Uno.Toolkit.WinUI.Material" Version="$(UnoToolkitVersion)" />
	
	<!-- Uno Extensions -->
    <PackageVersion Include="Uno.Extensions.Hosting" Version="$(UnoExtensionsVersion)" />
    <PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="$(UnoExtensionsVersion)" />	
    <PackageVersion Include="Uno.Extensions.Logging.Serilog" Version="$(UnoExtensionsVersion)" />
    <PackageVersion Include="Uno.Extensions.Logging.WinUI" Version="$(UnoExtensionsVersion)" />
    <PackageVersion Include="Uno.Extensions.Navigation" Version="$(UnoExtensionsVersion)" />
    <PackageVersion Include="Uno.Extensions.Navigation.WinUI" Version="$(UnoExtensionsVersion)" />
    <PackageVersion Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="$(UnoExtensionsVersion)" />
    <PackageVersion Include="Uno.Extensions.Reactive.WinUI" Version="$(UnoExtensionsVersion)" />
    <PackageVersion Include="Uno.Extensions.Toolkit.WinUI" Version="$(UnoExtensionsVersion)" />	
	
	<!-- Uno Extensions Logging -->
    <PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="$(UnoExtensionsLoggingVersion)" />
    <PackageVersion Include="Uno.Extensions.Logging.WebAssembly.Console" Version="$(UnoExtensionsLoggingVersion)" />
	
	<!-- Uno Material -->
    <PackageVersion Include="Uno.Material.WinUI" Version="$(UnoMaterialVersion)" />	
	
	<!-- Skia -->
	<PackageVersion Include="SkiaSharp.Skottie" Version="$(SkiaVersion)" />
    <PackageVersion Include="SkiaSharp.Views.Uno.WinUI" Version="$(SkiaVersion)" />	
	
	<!-- ReactiveUI -->
	<PackageVersion Include="ReactiveUI.Fody" Version="19.4.1" />
    <PackageVersion Include="ReactiveUI.Uno.WinUI" Version="19.1.1" />
		
	<!-- Android -->
    <PackageVersion Include="Xamarin.Google.Android.Material" Version="1.8.0" />
	
	<!-- Other -->
	<PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.0" />
    <PackageVersion Include="Mapsui.Uno.WinUI" Version="4.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0-preview.6.23329.7" />
    <PackageVersion Include="Microsoft.Windows.Compatibility" Version="8.0.0-preview.6.23329.4" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.3.230602002" />

    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
	
    <PackageVersion Include="Uno.Dsp.Tasks" Version="1.1.0" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.1.2" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
  </ItemGroup>
</Project>
