<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shmyndra.Mavlink.Generator\Shmyndra.Mavlink.Generator.csproj">
      <ReferenceOutputAssembly>False</ReferenceOutputAssembly>
      <OutputItemType>Analyzer</OutputItemType>
    </ProjectReference>
    <ProjectReference Include="..\Shmyndra.Mavlink\Shmyndra.Mavlink.csproj" />
  </ItemGroup>
  
  <!-- PropertyGroup for Mavlink.Generator setup -->
  <PropertyGroup>
    <GenerateEnumBitmaskTypes>true</GenerateEnumBitmaskTypes>
  </PropertyGroup>
  
  <!-- PropertyGroup for Debugging Generator --> 
  <PropertyGroup Condition="'$(BuildingInsideVisualStudio)' == 'true'">
    <CompilerGeneratedFilesOutputPath>Generated/Analyzers/netstandard$(TargetFramework)</CompilerGeneratedFilesOutputPath>
    <EmitCompilerGeneratedFiles>False</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <!-- ItemGroup for Debugging Generator -->
  <ItemGroup Condition="'$(BuildingInsideVisualStudio)' == 'true' AND '$(EmitCompilerGeneratedFiles)' == 'true'">
    <Compile Include="$(CompilerGeneratedFilesOutputPath)/**" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="**/*.xml" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Memory" />
  </ItemGroup>
</Project>
