namespace Shmyndra.Mavlink.Generator;

internal static class MavlinkGeneratorConstants
{
	public const string AutoGeneratedHeader =
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Shmyndra.Mavlink.Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";
}
