using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Shmyndra.Mavlink.Generator;

[Generator]
public class MavlinkIncrementalGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		if (!System.Diagnostics.Debugger.IsAttached)
		{
			//Uncomment this line to enter Debug mode for the generator and perform a Rebuild
			//System.Diagnostics.Debugger.Launch();
		}

		try
		{
			new Generator().Generate(context);
		}
		catch (Exception)
		{
			//context.ReportDiagnostic(
			//	Diagnostic.Create(
			//		MavlinkGeneratorDiagnostics.GenericProtocolErrorRule,
			//		Location.None,
			//		ex.Message
			//	)
			//);
		}
	}

	class Generator
	{
		private static readonly IMavlinkTreeBuilder _treeBuilder = new MavlinkTreeBuilder(new MavlinkXmlParser());

		internal void Generate(IncrementalGeneratorInitializationContext context)
		{
			var xmlFiles = context.AdditionalTextsProvider
				.Where(file => file.Path.EndsWith(".xml")
					// Files that are not included in the project marked as "_"
					&& !Path.GetFileName(file.Path).StartsWith("_"))
				.Select((file, _) => (file.Path, Content: file.GetText()!.ToString()))
				.Collect();

			var compilationAndFiles = context.CompilationProvider.Combine(xmlFiles);
			context.RegisterSourceOutput(compilationAndFiles, GenerateSourceFiles);
		}

		private void GenerateSourceFiles(SourceProductionContext spc, (Compilation Compilation, ImmutableArray<(string Path, string Content)> Files) input)
		{
			var (compilation, files) = input;

			var messageGenerator = GetMavlinkMessageGeneratorInstanceWithNetStandardCondition(compilation);

			var generator = new MavlinkGenerator(
				new MavlinkTreeBuilder(new MavlinkXmlParser()),
				enumGenerator,
				messageGenerator,
				new MavlinkSpecificationGenerator());

			var filesDictionary = files.ToImmutableDictionary(item => item.Path, item => item.Content);
			var generatedFiles = generator.GenerateMavlink(filesDictionary);

			foreach (var generatedFile in generatedFiles.Values)
			{
				AddSource(spc, generatedFile.Namespace, generatedFile.Syntax);
			}

			var messagesStorage = (IGeneratedStorage<GeneratedMavlinkMessage>)messageGenerator;
			var generatedMessages = messagesStorage.GetGeneratedTypes();
			var generatedMessagesSourceCode = MavlinkMessagesGenerator.GenerateMessageExtensions(generatedMessages);
			AddSource(spc, MavlinkGeneratorConstants.TypesNamespace, generatedMessagesSourceCode);
		}

		private MavlinkMessageGenerator GetMavlinkMessageGeneratorInstanceWithNetStandardCondition(Compilation compilation)
		{
			bool supportsSpan = IsSpanSerializationAvailable(compilation);

			if (supportsSpan)
			{
				return new MavlinkMessageGenerator
				(

					new MavlinkMessageDeserializationMethodGenerator
					(
						new MavlinkSpanDeserializationGeneratorStrategy()
					),
					new MavlinkMessageSerializationMethodGenerator
					(
						new MavlinkSpanSerializationGeneratorStrategy()
					)
				);
			}

			return new MavlinkMessageGenerator
			(
				new MavlinkMessageDeserializationMethodGenerator
				(
					new MavlinkBufferDeserializationGeneratorStrategy()
				),
				new MavlinkMessageSerializationMethodGenerator
				(
					new MavlinkBufferSerializationGeneratorStrategy()
				)
			);
		}

		private static bool IsSpanSerializationAvailable(Compilation compilation)
		{
			var bitConverterSymbol = compilation.GetTypeByMetadataName("System.BitConverter");
			if (bitConverterSymbol != null)
			{
				var hasSingleToInt32Bits = bitConverterSymbol.GetMembers("SingleToInt32Bits")
					.OfType<IMethodSymbol>()
					.Any(method =>
						 method.Parameters.Length == 1 &&
						 method.Parameters[0].Type.SpecialType == SpecialType.System_Single &&
						 method.ReturnType.SpecialType == SpecialType.System_Int32);
				return hasSingleToInt32Bits;
			}
			return false;
		}

		private void AddSource(SourceProductionContext context, string fileName, CompilationUnitSyntax syntax)
		{
			var sourceText = MavlinkGeneratorConstants.AutoGeneratedHeader + "\n" + syntax.ToNormalizedString();
			context.AddSource($"{fileName}.g.cs", SourceText.From(sourceText, Encoding.UTF8));
		}

		private void AddSource(SourceProductionContext context, string fileName, string sourceText)
		{
			sourceText = MavlinkGeneratorConstants.AutoGeneratedHeader + "\n" + sourceText;
			context.AddSource($"{fileName}.g.cs", SourceText.From(sourceText, Encoding.UTF8));
		}
	}
}
