using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Shmyndra.Mavlink.Generator;

[Generator]
public class MavlinkIncrementalGenerator : IIncrementalGenerator, IDisposable
{
	private readonly IMavlinkFilesTreeBuilder _treeBuilder;
	private readonly MavlinkMemberDefinition _contentGenerator;
	private readonly AssemblyResolver _assemblyResolver;
	private bool _disposed;
	private readonly HashSet<string> _generatedFiles = new();

	public MavlinkIncrementalGenerator()
		: this(
			new MavlinkFilesTreeBuilder(new MavlinkXmlParser()),
			new MavlinkEnumTypesGenerator(),
			new MavlinkMessageTypesGenerator(),
			new MavlinkSpecificationTypeGenerator())
	{
	}

	internal MavlinkIncrementalGenerator(
		IMavlinkFilesTreeBuilder treeBuilder,
		IMavlinkEnumTypesGenerator enumGenerator,
		IMavlinkMessageTypesGenerator messageGenerator,
		IMavlinkSpecificationTypeGenerator specificationGenerator)
	{
		_treeBuilder = treeBuilder;
		_contentGenerator = new MavlinkMemberDefinition(enumGenerator, messageGenerator, specificationGenerator);
		_assemblyResolver = new AssemblyResolver("System.ComponentModel.Annotations");
	}

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		if (!System.Diagnostics.Debugger.IsAttached)
		{
			//Uncomment this line to enter Debug mode for the generator and perform a Rebuild
			System.Diagnostics.Debugger.Launch();
		}
		RegisterSourceGeneration(context);
	}

	private void RegisterSourceGeneration(IncrementalGeneratorInitializationContext context)
	{
		var xmlFiles = context.AdditionalTextsProvider
			.Where(file => file.Path.EndsWith(".xml")
				// Files that are not included in the project marked as "_"
				&& !Path.GetFileName(file.Path).StartsWith("_"))
			.Select((file, _) => (file.Path, Content: file.GetText()!.ToString()))
			.Collect();
		context.RegisterSourceOutput(xmlFiles, GenerateSourceFiles);
	}

	private void GenerateSourceFiles(SourceProductionContext sourceProductionContext, ImmutableArray<(string Path, string Content)> files)
	{
		try
		{
			var messagesCache = new List<MavlinkCachedMessage>();
			var fileContents = files.ToDictionary(f => f.Path, f => f.Content);
			var rootFileTrees = _treeBuilder.Build(fileContents);

			foreach (var rootFileTree in rootFileTrees)
			{
				ProcessFileTree(sourceProductionContext, rootFileTree, messagesCache);
			}

			if (messagesCache.Count > 0)
			{
				var cachedMessagesCode = MavlinkCachedMessagesGenerator.GenerateMessagesCache(messagesCache);
				var cachedMessagesCodeWithHeader = MavlinkGeneratorConstants.AutoGeneratedHeader + "\n" + cachedMessagesCode;
				sourceProductionContext.AddSource($"MavlinkTypes.g.cs", SourceText.From(cachedMessagesCodeWithHeader, Encoding.UTF8));
			}
		}
		catch (Exception ex)
		{
			sourceProductionContext.ReportDiagnostic(
				Diagnostic.Create(
					MavlinkGeneratorDiagnostics.GenericProtocolErrorRule,
					Location.None,
					ex.Message
				)
			);
		}
	}

	private void ProcessFileTree(
		SourceProductionContext context,
		MavlinkFilesTreeBuilder.MavlinkFileNode node,
		List<MavlinkCachedMessage> messagesCache)
	{
		foreach (var include in node.Includes)
		{
			ProcessFileTree(context, include, messagesCache);
		}

		if (_generatedFiles.Contains(node.FilePath))
		{
			return;
		}

		var namespaceName = $"MavlinkTypes.{Utilities.ToCamelCase(Path.GetFileNameWithoutExtension(node.FilePath))}";

		var members = _contentGenerator.GenerateNamespaceMembers(node.Data, namespaceName, out var messagesCacheOut, node.FilePath);

		if (messagesCacheOut.Count > 0)
		{
			messagesCache.AddRange(messagesCacheOut);
		}

		AddSource(context, namespaceName, members);

		_generatedFiles.Add(node.FilePath);
	}

	private void AddSource(SourceProductionContext context, string namespaceName, List<MemberDeclarationSyntax> members)
	{
		var compilationUnit = SyntaxFactory.CompilationUnit()
			.AddMembers(SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(namespaceName))
			.AddMembers(members.ToArray()));

		var sourceText = MavlinkGeneratorConstants.AutoGeneratedHeader + "\n" + compilationUnit.NormalizeWhitespace().ToFullString();
		context.AddSource($"{namespaceName}.g.cs", SourceText.From(sourceText, Encoding.UTF8));
	}

	public void Dispose()
	{
		Dispose(true);
		GC.SuppressFinalize(this);
	}

	private void Dispose(bool disposing)
	{
		if (!_disposed)
		{
			if (disposing)
			{
				_assemblyResolver?.Dispose();
			}
			_disposed = true;
		}
	}

	~MavlinkIncrementalGenerator()
	{
		Dispose(false);
	}
}
