using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Shmyndra.Mavlink.Generator;

[Generator]
public class MavlinkIncrementalGenerator : IIncrementalGenerator, IDisposable
{
	private readonly AssemblyResolver _assemblyResolver;
	private bool _disposed;

	public MavlinkIncrementalGenerator()
	{
		_assemblyResolver = new AssemblyResolver("System.ComponentModel.Annotations");
	}

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		if (!System.Diagnostics.Debugger.IsAttached)
		{
			//Uncomment this line to enter Debug mode for the generator and perform a Rebuild
			//System.Diagnostics.Debugger.Launch();
		}

		try
		{
			new Generator().Generate(context);
		}
		catch (Exception)
		{
			//context.ReportDiagnostic(
			//	Diagnostic.Create(
			//		MavlinkGeneratorDiagnostics.GenericProtocolErrorRule,
			//		Location.None,
			//		ex.Message
			//	)
			//);
		}
	}

	class Generator
	{
		private static readonly IMavlinkFilesTreeBuilder _treeBuilder = new MavlinkFilesTreeBuilder(new MavlinkXmlParser());

		internal void Generate(IncrementalGeneratorInitializationContext context)
		{
			var xmlFiles = context.AdditionalTextsProvider
				.Where(file => file.Path.EndsWith(".xml")
					// Files that are not included in the project marked as "_"
					&& !Path.GetFileName(file.Path).StartsWith("_"))
				.Select((file, _) => (file.Path, Content: file.GetText()!.ToString()))
				.Collect();
			context.RegisterSourceOutput(xmlFiles, GenerateSourceFiles);
		}

		private void GenerateSourceFiles(SourceProductionContext sourceProductionContext, ImmutableArray<(string Path, string Content)> files)
		{
			var messageGenerator = new MavlinkMessageGenerator();
			var generator = new MavlinkGenerator(_treeBuilder, new MavlinkEnumGenerator(), messageGenerator, new MavlinkSpecificationGenerator());

			var filesDictionary = files.ToImmutableDictionary(item => item.Path, item => item.Content);
			var generatedFiles = generator.GenerateMavlink(filesDictionary);

			foreach (var generatedFile in generatedFiles.Values)
			{
				AddSource(sourceProductionContext, generatedFile.Namespace, generatedFile.Syntax);
			}

			var messagesStorage = (IGeneratedStorage<GeneratedMavlinkMessage>)messageGenerator;
			var generatedMessages = messagesStorage.GetGeneratedTypes();
			var generatedMessagesSourceCode = MavlinkMessagesGenerator.GenerateMessageExtensions(generatedMessages);
			AddSource(sourceProductionContext, MavlinkGeneratorConstants.TypesNamespace, generatedMessagesSourceCode);
		}

		private void AddSource(SourceProductionContext context, string fileName, CompilationUnitSyntax syntax)
		{
			var sourceText = MavlinkGeneratorConstants.AutoGeneratedHeader + "\n" + syntax.NormalizeWhitespace().ToFullString();
			context.AddSource($"{fileName}.g.cs", SourceText.From(sourceText, Encoding.UTF8));
		}

		private void AddSource(SourceProductionContext context, string fileName, string sourceText)
		{
			sourceText = MavlinkGeneratorConstants.AutoGeneratedHeader + "\n" + sourceText;
			context.AddSource($"{fileName}.g.cs", SourceText.From(sourceText, Encoding.UTF8));
		}
	}

	public void Dispose()
	{
		Dispose(true);
		GC.SuppressFinalize(this);
	}

	private void Dispose(bool disposing)
	{
		if (!_disposed)
		{
			if (disposing)
			{
				_assemblyResolver?.Dispose();
			}
			_disposed = true;
		}
	}

	~MavlinkIncrementalGenerator()
	{
		Dispose(false);
	}
}
