<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <PropertyGroup>
    <PolySharpIncludeGeneratedTypes>
      System.Diagnostics.CodeAnalysis.NotNullWhenAttribute;
      System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute;
      System.Index;
      System.Range;
    </PolySharpIncludeGeneratedTypes>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
    <PackageReference Include="PolySharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.ComponentModel.Annotations" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="Shmyndra.Mavlink.SourceGenerators.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shmyndra.Mavlink\Attributes\MavlinkTypeAttribute.cs">
      <Link>Attributes\MavlinkTypeAttribute.cs</Link>
    </Compile>
    <Compile Include="..\Shmyndra.Mavlink\Attributes\RequiredArrayLengthAttribute.cs">
      <Link>Attributes\RequiredArrayLengthAttribute.cs</Link>
    </Compile>
  </ItemGroup>
</Project>
