<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) or '$(EnableWindowsTargeting)' == 'true'">$(TargetFrameworks);net7.0-windows10.0.19041</TargetFrameworks>
		<TargetFrameworks>$(TargetFrameworks);net7.0;net7.0-ios;net7.0-android;net7.0-maccatalyst</TargetFrameworks>
		<GenerateLibraryLayout>true</GenerateLibraryLayout>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net7.0-windows10.0.19041'">
		<RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mapsui.Uno.WinUI" />
		<PackageReference Include="Uno.Dsp.Tasks" />
		<PackageReference Include="Uno.WinUI" />
		<PackageReference Include="Uno.Resizetizer" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="Uno.Extensions.Logging.WinUI" />
		<PackageReference Include="Uno.Extensions.Logging.Serilog" />
		<PackageReference Include="Uno.Material.WinUI" />
		<PackageReference Include="Uno.Toolkit.WinUI.Material" />
		<PackageReference Include="Uno.Extensions.Toolkit.WinUI" />
		<PackageReference Include="Uno.Toolkit.WinUI" />
		<PackageReference Include="Uno.Extensions.Hosting.WinUI" />
		<PackageReference Include="Uno.Extensions.Navigation.Toolkit.WinUI" />
		<PackageReference Include="Uno.Extensions.Navigation.WinUI" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" />
	</ItemGroup>

	<Choose>
		<When Condition="$(IsWinAppSdk)">
			<ItemGroup>
				<PackageReference Include="Microsoft.WindowsAppSDK" />
				<PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<Content Include="Assets\**" />
				<Page Include="**\*.xaml" Exclude="bin\**\*.xaml;obj\**\*.xaml" />
				<Compile Update="**\*.xaml.cs">
					<DependentUpon>%(Filename)</DependentUpon>
				</Compile>
				<PRIResource Include="**\*.resw" />
			</ItemGroup>
		</Otherwise>
	</Choose>

	<ItemGroup>
		<UnoDspImportColors Include="Styles\*.zip" Generator="Xaml" />
		<UnoImage Include="Assets\**\*.svg" />
		<UpToDateCheckInput Include="**\*.xaml" Exclude="bin\**\*.xaml;obj\**\*.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Pages\UnmannedVehiclesManagerPage.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Pages\UnmannedVehiclesManagerPage.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <AdditionalFiles Remove="Pages\UnmannedVehiclesManagerPage.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TerritoryDefence.UI.ViewModels\TerritoryDefence.UI.ViewModels.csproj" />
	</ItemGroup>
</Project>
