// <auto-generated/>
#nullable enable
namespace Mavlink.Common;

/// <summary>
/// Bitmask over <see cref="MavModeFlag"/>. Unknown bits received from the wire are preserved;
/// the wire width of a particular field is enforced by that field's serializer.
/// </summary>
public readonly struct MavModeFlagBitmask : IEquatable<MavModeFlagBitmask>
#if NET6_0_OR_GREATER
	, ISpanFormattable
#else
	, IFormattable
#endif
{
	/// <summary>
	/// Union of all single-bit <see cref="MavModeFlag"/> values.
	/// </summary>
	public const byte DefinedMask = 0xFF;

	/// <summary>
	/// Storage width in bits.
	/// </summary>
	public const int Width = 8;

	// One entry per set bit of DefinedMask, sorted by bit ascending.
	// BitmaskDisplay relies on this ordering for O(1) lookup.
	private static readonly BitmaskEntry[] Entries =
	{
		new(0, nameof(MavModeFlag.CustomModeEnabled), "MAV_MODE_FLAG_CUSTOM_MODE_ENABLED"),
		new(1, nameof(MavModeFlag.TestEnabled), "MAV_MODE_FLAG_TEST_ENABLED"),
		new(2, nameof(MavModeFlag.AutoEnabled), "MAV_MODE_FLAG_AUTO_ENABLED"),
		new(3, nameof(MavModeFlag.GuidedEnabled), "MAV_MODE_FLAG_GUIDED_ENABLED"),
		new(4, nameof(MavModeFlag.StabilizeEnabled), "MAV_MODE_FLAG_STABILIZE_ENABLED"),
		new(5, nameof(MavModeFlag.HilEnabled), "MAV_MODE_FLAG_HIL_ENABLED"),
		new(6, nameof(MavModeFlag.ManualInputEnabled), "MAV_MODE_FLAG_MANUAL_INPUT_ENABLED"),
		new(7, nameof(MavModeFlag.SafetyArmed), "MAV_MODE_FLAG_SAFETY_ARMED"),
	};

	private readonly byte _bits;

	private MavModeFlagBitmask(byte bits) => _bits = bits;

	public MavModeFlagBitmask(MavModeFlag value) : this((byte)value) { }

	public static MavModeFlagBitmask Empty => default;

	/// <summary>
	/// Wraps raw wire bits without validation. Unknown bits are preserved.
	/// </summary>
	public static MavModeFlagBitmask FromRaw(byte bits) => new(bits);

	public byte Bits => _bits;

	/// <summary>
	/// Enum view of the mask. Bits outside the enum's width are dropped; see <see cref="UnknownBits"/>.
	/// </summary>
	public MavModeFlag Value => (MavModeFlag)unchecked((byte)_bits);

	public int Count => BitHelper.PopCount((ulong)(_bits & DefinedMask));
	public bool IsEmpty => _bits == 0;
	public byte UnknownBits => (byte)(_bits & ~DefinedMask);
	public bool HasUnknownBits => UnknownBits != 0;

	/// <summary>
	/// True if every bit of <paramref name="flag"/> is set. Works for composite values too.
	/// </summary>
	public bool Has(MavModeFlag flag)
	{
		byte f = (byte)flag;
		return f != 0 && (_bits & f) == f;
	}

	public bool HasAny(MavModeFlag flags) => (_bits & (byte)flags) != 0;

	public MavModeFlagBitmask With(MavModeFlag flag, bool value) => value
		? new((byte)(_bits | (byte)flag))
		: new((byte)(_bits & ~(byte)flag));

	public FlagEnumerator<MavModeFlag> GetEnumerator() => new((ulong)(_bits & DefinedMask));

	public BitmaskDisplay ToDisplay() => BitmaskDisplay.Named(_bits, Width, DefinedMask, Entries);

	public static implicit operator MavModeFlagBitmask(MavModeFlag value) => new(value);

	public static MavModeFlagBitmask operator |(MavModeFlagBitmask l, MavModeFlagBitmask r) => new((byte)(l._bits | r._bits));
	public static MavModeFlagBitmask operator &(MavModeFlagBitmask l, MavModeFlagBitmask r) => new((byte)(l._bits & r._bits));
	public static MavModeFlagBitmask operator ^(MavModeFlagBitmask l, MavModeFlagBitmask r) => new((byte)(l._bits ^ r._bits));

	/// <summary>
	/// Complement within the defined flags. Unknown bits are cleared.
	/// </summary>
	public static MavModeFlagBitmask operator ~(MavModeFlagBitmask v) => new((byte)(~v._bits & DefinedMask));

	public bool Equals(MavModeFlagBitmask other) => _bits == other._bits;
	public override bool Equals(object? obj) => obj is MavModeFlagBitmask other && Equals(other);
	public override int GetHashCode() => _bits.GetHashCode();
	public static bool operator ==(MavModeFlagBitmask l, MavModeFlagBitmask r) => l._bits == r._bits;
	public static bool operator !=(MavModeFlagBitmask l, MavModeFlagBitmask r) => l._bits != r._bits;

	public override string ToString() => ToDisplay().ToString();
	public string ToString(string? format, IFormatProvider? provider) => ToDisplay().ToString(format, provider);

#if NET6_0_OR_GREATER
	public bool TryFormat(Span<char> destination, out int charsWritten,
		ReadOnlySpan<char> format, IFormatProvider? provider) =>
		ToDisplay().TryFormat(destination, out charsWritten, format, provider);
#endif
}
