<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) or '$(EnableWindowsTargeting)' == 'true'">$(TargetFrameworks);net8.0-windows10.0.19041</TargetFrameworks>
		<TargetFrameworks>$(TargetFrameworks);net8.0;net8.0-ios;net8.0-maccatalyst;net8.0-android</TargetFrameworks>
		<GenerateLibraryLayout>true</GenerateLibraryLayout>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Uno.WinUI" />
	</ItemGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows10.0.19041'">
		<RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
	</PropertyGroup>
	
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
		<PackageReference Include="CommunityToolkit.WinUI.UI.Behaviors" />
	</ItemGroup>
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'windows'">
		<PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Behaviors" />
	</ItemGroup>
	
	<Choose>
		<When Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
			<ItemGroup>
				<PackageReference Include="Microsoft.WindowsAppSDK" />
				<PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<PriResource Include="**\*.resw" />
			</ItemGroup>
		</Otherwise>
	</Choose>
	<ItemGroup>
		<UpToDateCheckInput Include="**\*.xaml" Exclude="bin\**\*.xaml;obj\**\*.xaml" />
	</ItemGroup>
</Project>