<Project>
  <PropertyGroup>
    <!-- Check if the target framework is netstandard2.0 -->
    <Condition1 Condition="'$(TargetFramework)' == 'netstandard2.0'">true</Condition1>
    <Condition1 Condition="'$(Condition1)' == ''">false</Condition1>

    <!-- Check if the target framework is netstandard2.1 -->
    <Condition2 Condition="'$(TargetFramework)' == 'netstandard2.1'">true</Condition2>
    <Condition2 Condition="'$(Condition2)' == ''">false</Condition2>

    <!-- Check if netstandard2.0 is included in TargetFrameworks -->
    <Condition3 Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(TargetFrameworks)', '(^|;|,)\s*netstandard2\.0\s*(;|,|$)'))">true</Condition3>
    <Condition3 Condition="'$(Condition3)' == ''">false</Condition3>

    <!-- Check if netstandard2.1 is included in TargetFrameworks -->
    <Condition4 Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(TargetFrameworks)', '(^|;|,)\s*netstandard2\.1\s*(;|,|$)'))">true</Condition4>
    <Condition4 Condition="'$(Condition4)' == ''">false</Condition4>

    <!-- Define separate conditions for netstandard2.0 and netstandard2.1 -->
    <IsNetStandard2_0Condition Condition="'$(Condition1)' == 'true' OR '$(Condition3)' == 'true'">true</IsNetStandard2_0Condition>
    <IsNetStandard2_1Condition Condition="'$(Condition2)' == 'true' OR '$(Condition4)' == 'true'">true</IsNetStandard2_1Condition>

    <!-- Unified condition that checks for either netstandard2.0 or netstandard2.1 -->
    <IsNetStandardCondition Condition="'$(IsNetStandard2_0Condition)' == 'true' OR '$(IsNetStandard2_1Condition)' == 'true'">true</IsNetStandardCondition>
  </PropertyGroup>

  <Import Project="PolySharp.targets" />
</Project>
