<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <DebugType>portable</DebugType>
    <DebugSymbols>True</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup>
    <Copyright>Copyright © limeniye 2023</Copyright>
    <Authors>limeniye</Authors>
  </PropertyGroup>

  <PropertyGroup>
    <DotNetVersion>net8.0</DotNetVersion>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <PropertyGroup>
    <DebugType>portable</DebugType>
    <DebugSymbols>True</DebugSymbols>
    <NoWarn>Uno0001;CS1998;CA1416;NU1504;NU1505;NU1507</NoWarn>
    <WarningsNotAsErrors>CS0618</WarningsNotAsErrors>
    <SynthesizeLinkMetadata>true</SynthesizeLinkMetadata>
  </PropertyGroup>
</Project>
