<Project ToolsVersion="15.0">
  <!-- Properties -->
  <PropertyGroup>
    <MicrosoftBuildVersion>18.8.2</MicrosoftBuildVersion>
    <xunitVersion>3.1.5</xunitVersion>
  </PropertyGroup>

  <!-- Generator packages -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Build.Framework" Version="$(MicrosoftBuildVersion)" />
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="$(MicrosoftBuildVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.6.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
    <PackageVersion Include="Scriban.Signed" Version="7.2.6" />
  </ItemGroup>

  <!-- Test packages -->
  <ItemGroup>
    <PackageVersion Include="FluentAssertions" Version="8.10.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Verify.SourceGenerators" Version="2.5.0" />
    <PackageVersion Include="Verify.Xunit" Version="31.12.5" />
    <PackageVersion Include="xunit" Version="$(xunitVersion)" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="$(xunitVersion)" />
  </ItemGroup>

  <!-- Shared packages -->
  <ItemGroup>
    <PackageVersion Include="PolySharp" Version="1.16.0" />
    <PackageVersion Include="System.Collections.Immutable" Version="10.0.10" />
    <PackageVersion Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageVersion Include="System.Memory" Version="4.6.3" />
    <PackageVersion Include="System.IO.Pipelines" Version="10.0.10" />
    <PackageVersion Include="System.IO.Ports" Version="10.0.10" />
    <PackageVersion Include="System.Threading.Channels" Version="10.0.10" />
    <PackageVersion Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
  </ItemGroup>
</Project>
