<Project>
  <ItemGroup Condition="'$(IsNetStandardCondition)' == 'true'">
    <PackageReference Include="PolySharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup Condition="'$(IsNetStandard2_0Condition)' == 'true'">
    <PolySharpIncludeGeneratedTypes>
      System.Diagnostics.CodeAnalysis.NotNullWhenAttribute;
      System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute;
      System.Index;
      System.Range;
      System.Runtime.CompilerServices.IsExternalInit;
      System.Runtime.CompilerServices.SkipLocalsInitAttribute;
      System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute;
      System.Runtime.CompilerServices.RequiredMemberAttribute;
    </PolySharpIncludeGeneratedTypes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsNetStandard2_1Condition)' == 'true'">
    <PolySharpIncludeGeneratedTypes>
      System.Runtime.CompilerServices.IsExternalInit;
      System.Runtime.CompilerServices.SkipLocalsInitAttribute;
      System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute;
      System.Runtime.CompilerServices.RequiredMemberAttribute;
    </PolySharpIncludeGeneratedTypes>
  </PropertyGroup>
</Project>
